### PR TITLE
Fixes for building with LibreSSL

### PR DESCRIPTION
**Pull request by Sp1l**
During a build of curl with LibreSSL as SSL library the build fails due to detecting an unavailable function during configure.
What I've noticed is that the order in which the libraries are searched differs between 10.0/clang3.3 and 10.1/clang3.4 This simply disables SRP making the build succeed.

This pull request now includes fixes for most of the ports that failed in the earlier run.

### CODE REVIEW

**Comment by kmoore134** [comment]
Thanks for adding these! I'm kicking off a build now, you can watch it here:

http://builds.pcbsd.org:8880/build.html?mastername=pcbsd-100-RELEASE-1012&build=2015-02-22_18h43m50s

I'll ping back with any failures :)

**Comment by kmoore134** [comment]
Ok, the build is still running, but looks like we have a dozen or so failures so far. Here's some of the biggest blockers:

http://builds.pcbsd.org:8880/data/pcbsd-100-RELEASE-1012/2015-02-22_18h43m50s/logs/errors/qca-2.1.0_1.log

http://builds.pcbsd.org:8880/data/pcbsd-100-RELEASE-1012/2015-02-22_18h43m50s/logs/errors/python34-3.4.2_1.log

http://builds.pcbsd.org:8880/data/pcbsd-100-RELEASE-1012/2015-02-22_18h43m50s/logs/errors/wget-1.16.log

http://builds.pcbsd.org:8880/data/pcbsd-100-RELEASE-1012/2015-02-22_18h43m50s/logs/errors/py27-pip-6.0.8.log

http://builds.pcbsd.org:8880/data/pcbsd-100-RELEASE-1012/2015-02-22_18h43m50s/logs/errors/libxul-31.4.0_2.log

http://builds.pcbsd.org:8880/data/pcbsd-100-RELEASE-1012/2015-02-22_18h43m50s/logs/errors/Ice-3.5.1_6.log

**Comment by kmoore134** [comment]
I just added this fix to devel/qca

https://github.com/pcbsd/freebsd-ports/commit/bdb8488ff68c17d8e884164fa1db9f9eb74efd73

**Comment by Sp1l** [comment]
Then we're duplicating work, so have I :D
https://github.com/Sp1l/ports/commit/0a9dfabfcbf9f0ce2c33376c7a8556818fd65ef1

**Comment by kmoore134** [comment]
Opps! I will wait for you to issue another pull request then, since
you've already got several fixes in :)

The build is still running, but I'll keep kicking off others when you
send me a request. It would be great to get our next EDGE package set
this week out with libressl on, so we can start doing real-world testing.

On 02/23/2015 12:23, Bernard Spil wrote:
>
> Then we're duplicating work, so have I :D
> Sp1l/ports@0a9dfab
> <https://github.com/Sp1l/ports/commit/0a9dfabfcbf9f0ce2c33376c7a8556818fd65ef1>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcbsd/freebsd-ports/pull/10#issuecomment-75588432>.
>


-- 
Kris Moore
PC-BSD Software
iXsystems

**Comment by Sp1l** [comment]
Creating a pull request now... 
My own Poudriere logs are also available now (not yet for the pcbsd build I had done)

**Pull request merged**
