### PR TITLE
Final batch of LibreSSL fixes for now

### PR DESCRIPTION
**Pull request by Sp1l**
That should do for now, I may look at the GOST problems still.

### CODE REVIEW

**Comment by kmoore134** [comment]
Thanks! I'll get a build with those going tomorrow sometime.

**Comment by Sp1l** [comment]
Current 11 build has a lot of net-snmp fall-out.
Dunno if you had already seen this
https://lists.freebsd.org/pipermail/svn-src-head/2015-February/068674.html

**Comment by kmoore134** [comment]
Yea, I'm looking and not finding any patches floating around with fixes yet. Do you know of any at the moment?

**Comment by Sp1l** [comment]
Saw it and tried to find a patch of sorts. Then ran into that ML post and shied away :/

**Pull request merged**
