### PR TITLE
Next batch of LibreSSL fixes

### PR DESCRIPTION
**Pull request by Sp1l**
Fix irc/unreal buid with LibreSSL (EGD)
Fix security/opencryptoki (deprecated des_* methods to DES_*)
Fix databases/virtuoso (deprecated des_* methods to DES_*) NOT BUILD-TESTED!!!
Fix devel/ice (EGD)

### CODE REVIEW

**Comment by kmoore134** [comment]
Merged in! I'll kickoff another run now, thanks!

**Comment by Sp1l** [comment]
Dunno if it's of any help to you
   https://wiki.freebsd.org/LibreSSL
Comments appreciated!

**Comment by kmoore134** [comment]
Sure! Part of the problem with anything like this is the lack of information, so this will be handy for me, and to get others involved :)

**Comment by Sp1l** [comment]
Tried to rally a bit on #bsdports and #freebsd but noone took the bait just yet :D Trying to get my complete info into the wiki that I've collected along the way.

**Comment by kmoore134** [comment]
Next build is running now:

http://builds.pcbsd.org:8880/build.html?mastername=pcbsd-100-RELEASE-1012&build=2015-02-27_09h38m29s

I'll have to jump into #bsdports in case you need to get ahold of me.

**Pull request merged**
